### PR TITLE
Carlin Simserver Fixes

### PR DESCRIPTION
**Pull request by CarlinWilliamson**
Changes to get Sid's simserver working

### CODE REVIEW

**Review by jayenashar — APPROVED** [review]
i can guess from the changed lines why we need them, but my questions are:

1) does @siddhantvirmani have other uncommitted changes?
2) should we be able to handle beam noise?  in this way, simulations with the "same" starting position could have different outcomes and it seems important to know if we can handle those, rather than assuming reproducibility.

**Comment by s1z5d** [comment]
This was it from my side. 

Re beam noise, there's no problem handling it as such - it was only removed because simserver already does some random placement for multiple simulations and it seemed pointless to double the error. We could leave it in there however and perhaps just have some sort of instructions somewhere (perhaps simserver's readme) on how to turn it off.

**Comment by jayenashar** [comment]
could simserver change the file `$RUNSWIFT_CHECKOUT_DIR/softwares/simspark/rcssserver3d/installed/share/rcssserver3d/naosoccersim.rb` at runtime?

**Comment by s1z5d** [comment]
What would be the best way to do that? We'd also have to do a new build and then change it back once the app is turned off. 

If I were to do it, I'd do it in the python files itself - but again, we'd have to build again and change it back.

**Comment by jayenashar** [comment]
Changing a ruby file requires a rebuild?  Are you sure?  I don't think it's too big a deal if it's not reverted when rcssserver3d exits, but yeah it would be better if it was reverted.

**Comment by s1z5d** [comment]
Just checked - yeah it definitely requires a build.

**Comment by jayenashar** [comment]
oh ok, then let's have it as 0 in git.  @CarlinWilliamson i'll give you merge access if you don't have it already.

**Pull request merged**
